# final kernel binary name
NAME      = kernel.bin
# bootable ISO image name
ISO       = kernel.iso

# cross-compiler targeting bare-metal i386 (no OS)
CC        = i686-elf-gcc
# assembler for boot.asm
ASM       = nasm
# compilation flags:
# -fno-builtin			: disables GCC built-in functions (no runtime available)
# -fno-stack-protector	: disables stack protection (requires runtime support)
# -nostdlib				: no standard library
# -nodefaultlibs		: no default libraries
# -I include			: tells the compiler where to find header files
CFLAGS    = -fno-builtin -fno-stack-protector -nostdlib -nodefaultlibs -I include

# C source files to compile
C_SRCS    =	drivers/vga.c \
			kernel/kmain.c \

# ASM source files to compile
ASM_SRCS  = boot/boot.asm

# generates object files paths in obj/ from ASM sources
# $(ASM_SRCS:.asm=.o) replaces .asm with .o
# $(notdir ...) strips the directory path, keeping only the filename
# $(addprefix obj/, ...) prepends obj/ to each filename
ASM_OBJ   =	$(addprefix obj/, $(notdir $(ASM_SRCS:.asm=.o)))

# same operation for C sources
C_OBJ     =	$(addprefix obj/, $(notdir $(C_SRCS:.c=.o)))

# all object files combined
OBJ       = $(ASM_OBJ) $(C_OBJ)

# tells Make where to look for .asm source files
vpath %.asm boot
# tells Make where to look for .c source files
vpath %.c drivers kernel

# default target: builds the ISO
all: $(ISO)

# builds the ISO from the kernel binary
# copies kernel.bin into iso/boot then generates the ISO with GRUB
$(ISO): $(NAME)
	cp $(NAME) iso/boot/
	grub-mkrescue -o $(ISO) iso/

# links all object files into the final kernel binary
# -T linker.ld		: uses our custom linker script
# -ffreestanding	: freestanding environment, no OS assumptions
# -nostdlib			: no standard library at link stage
$(NAME): $(OBJ)
	$(CC) -T linker.ld -o $(NAME) -ffreestanding -nostdlib $(OBJ)

# compiles each .asm file into a ,o in obj/
# $< = the source file, $@ = the target file
# | obj means obj/ must exist before this rules runs
obj/%.o: %.asm | obj
	$(ASM) -f elf32 $< -o $@

# compiles each .c file into a .o in obj/
obj/%.o: %.c | obj
	$(CC) $(CFLAGS) -c $< -o $@

# creates the obj/ directory if it does not exist
obj:
	mkdir -p obj

# builds the ISO and launches the kernel in QEMU
run: $(ISO)
	qemu-system-i386 -cdrom $(ISO)

# removes all object files and the obj/ directory
clean:
	rm -f $(OBJ)
	rm -rf obj/

# removes everything generated by the build
fclean: clean
	rm -f $(NAME) $(ISO) iso/boot/kernel.bin

# full rebuild from scratch
re: fclean all

# declares targets that are not actual files
# prevents conflicts if a file with the same name exists
.PHONY: all run clean fclean re obj